name: test

on:
  push:
    branches:
      - "main"
      - "master"
      - "dev"
    paths:
      - "**.py"
      - ".github/workflows/*test*.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements/requirements*.txt"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/*test*.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements/requirements*.txt"

permissions:
  contents: read

concurrency:
  group: "test-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  test:
    name: "test Python ${{ matrix.python }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.11", "3.12", "3.13", "3.14"]
        include:
          - os: "macos-latest"
            python: "3.13"
    defaults:
      run:
        shell: "bash -eo pipefail {0}"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python }}"
          cache: "pip"
          cache-dependency-path: "requirements/requirements*.txt"
      - run: "python3 -mpip install -r requirements/requirements.txt -r requirements/requirements-dev.txt"
      - run: "python3 -mpip install ./"
      - run: "mypy src/pysubstream"
      - run: "make cov"
